### ISSUE TITLE
Error when trying to view task

### ISSUE THREAD

**Issue by TygheVallard** [soywod/kronos.vim#17] opened 2019-05-14 13:34 UTC
This happens after I view a task with `K` and then try to view it again
```
Error detected while processing function kronos#ui#info:
line   11:
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
```

**Comment by soywod** [comment] 2019-05-14 14:03
I can't reproduce. Could you provide me:

- Your environment (platform, vim/nvim version...)
- A precise scenario to reproduce

**Comment by necrolyte2** [comment] 2019-05-15 13:06
- MacOS 10.14.3
- VIM 8.1.950

1. Open VIM
1. `:Kronos`
1. Hover over row that you want to view and press `K`(This works as expected)
![Screen Shot 2019-05-15 at 8 05 32 AM](https://user-images.githubusercontent.com/378659/57777794-4d20db80-76e8-11e9-9801-54119694da20.png)

1. Close quick edit window that opens with info
1. Press `K` again
![Screen Shot 2019-05-15 at 8 05 46 AM](https://user-images.githubusercontent.com/378659/57777817-5a3dca80-76e8-11e9-889f-8f0d3ffe330e.png)

**Comment by soywod** [comment] 2019-05-15 13:53
Fixed with last commit https://github.com/soywod/kronos.vim/commit/8e9dd10f163a0394d3051411156f2572e327ad9e, buffer where not killed properly.

**Closed by soywod** 2019-05-15 13:53 UTC
Labels: bug
